# Generated by Django 5.2.5 on 2026-06-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_note_author_note_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='file',
            field=models.FileField(default='Admin', upload_to='notes/'),
            preserve_default=False,
        ),
    ]
