# Generated by Django 5.2.5 on 2026-06-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0003_note_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notes/'),
        ),
    ]
